export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const RECEIVE_SCHEDULE = 'RECEIVE_SCHEDULE';
export const RECEIVE_ACTIVITIES = 'RECEIVE_ACTIVITIES';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
